/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redesmonopolyserver.Pantallas;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import redesmonopolyserver.Comunicacion.Cliente;
import redesmonopolyserver.Dominio.CPropiedad;
import redesmonopolyserver.Dominio.Casilla;
import redesmonopolyserver.Dominio.Jugador;
import redesmonopolyserver.Dominio.Tablero;
import redesmonopolyserver.Persistencia.Generador;
import redesmonopolyserver.Persistencia.Usuario;

/**
 *
 * @author alexd
 */
public class PantallaJugadorPrincipal extends javax.swing.JFrame {
    Cliente cliente;
    boolean enAnimacion;

    /**
     * Creates new form PantallaJugadorPrincipal
     */
    public PantallaJugadorPrincipal() {
        initComponents();
        
        
    }
    
    public PantallaJugadorPrincipal(Cliente cliente) {
        initComponents();
        this.cliente=cliente;
        cliente.setPantalla(this);
        actualizarTablero(cliente.getTablero());
        setLocationRelativeTo(null);
        notificacion.setVisible(false);
        piezaJugador1.setVisible(false);
        piezaJugador2.setVisible(false);
        piezaJugador3.setVisible(false);
        piezaJugador4.setVisible(false);
        imagenJugador2.setVisible(false);
        imagenJugador3.setVisible(false);
        imagenJugador4.setVisible(false);
        dinero.setVisible(false);
        imagenJugador.setVisible(false);
        casas.setVisible(false);
        hoteles.setVisible(false);
        tableroYFondo.setVisible(false);
        panelNotificacion.setVisible(false);
        //cliente.solicitarTablero();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtClave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        panelNotificacion = new javax.swing.JPanel();
        notificacion = new javax.swing.JPanel();
        tituloNotificacion = new javax.swing.JLabel();
        textoNotificacion = new javax.swing.JLabel();
        textoNotificacion2 = new javax.swing.JLabel();
        aceptarNotificacion = new javax.swing.JButton();
        fondoNotificacion = new javax.swing.JLabel();
        tableroYFondo = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        areaJugador = new javax.swing.JPanel();
        imagenJugador = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        hoteles = new javax.swing.JLabel();
        casas = new javax.swing.JLabel();
        imagenJugador2 = new javax.swing.JLabel();
        imagenJugador3 = new javax.swing.JLabel();
        imagenJugador4 = new javax.swing.JLabel();
        piezaJugador1 = new javax.swing.JLabel();
        piezaJugador2 = new javax.swing.JLabel();
        piezaJugador3 = new javax.swing.JLabel();
        piezaJugador4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1010, 710));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1010, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(205, 230, 208));
        panelLogin.setMaximumSize(new java.awt.Dimension(1010, 710));
        panelLogin.setMinimumSize(new java.awt.Dimension(1010, 710));
        panelLogin.setName(""); // NOI18N
        panelLogin.setOpaque(false);
        panelLogin.setPreferredSize(new java.awt.Dimension(1010, 710));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        tituloLogin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLogin.setText("Inicion de Sesión");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Clave");

        jtUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jtUsuario.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtClave.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtClave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloLogin)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtClave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        panelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 410, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelNotificacion.setBackground(new java.awt.Color(205, 230, 208));
        panelNotificacion.setMaximumSize(new java.awt.Dimension(1010, 710));
        panelNotificacion.setMinimumSize(new java.awt.Dimension(1010, 710));
        panelNotificacion.setName(""); // NOI18N
        panelNotificacion.setOpaque(false);
        panelNotificacion.setPreferredSize(new java.awt.Dimension(1010, 710));
        panelNotificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notificacion.setOpaque(false);
        notificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloNotificacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tituloNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNotificacion.setText("Arca Comunal");
        notificacion.add(tituloNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        textoNotificacion.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        textoNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNotificacion.setText(".");
        notificacion.add(textoNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, -1));

        textoNotificacion2.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        textoNotificacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNotificacion2.setText(".");
        notificacion.add(textoNotificacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, -1));

        aceptarNotificacion.setText("Aceptar");
        aceptarNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarNotificacionActionPerformed(evt);
            }
        });
        notificacion.add(aceptarNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        fondoNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoNotificacion.png"))); // NOI18N
        notificacion.add(fondoNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelNotificacion.add(notificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 150));

        getContentPane().add(panelNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tableroYFondo.setBackground(new java.awt.Color(205, 230, 208));
        tableroYFondo.setMaximumSize(new java.awt.Dimension(1010, 710));
        tableroYFondo.setMinimumSize(new java.awt.Dimension(1010, 710));
        tableroYFondo.setName(""); // NOI18N
        tableroYFondo.setOpaque(false);
        tableroYFondo.setPreferredSize(new java.awt.Dimension(1010, 710));
        tableroYFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        tableroYFondo.add(botonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));
        botonJugar.getAccessibleContext().setAccessibleName("botonJugar");

        dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D1.png"))); // NOI18N
        tableroYFondo.add(dado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 125, -1, -1));

        dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D1.png"))); // NOI18N
        tableroYFondo.add(dado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 125, -1, -1));

        areaJugador.setOpaque(false);

        imagenJugador.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        imagenJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroG.png"))); // NOI18N
        imagenJugador.setText("Alex");
        imagenJugador.setToolTipText("");
        imagenJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagenJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        dinero.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        dinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dinero.png"))); // NOI18N
        dinero.setText("0");

        hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HotelG.png"))); // NOI18N
        hoteles.setText("0");

        casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CasaG.png"))); // NOI18N
        casas.setText("0");

        imagenJugador2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        imagenJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroM.png"))); // NOI18N
        imagenJugador2.setText("Alex");
        imagenJugador2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imagenJugador2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagenJugador2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        imagenJugador3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        imagenJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroM.png"))); // NOI18N
        imagenJugador3.setText("Alex");
        imagenJugador3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imagenJugador3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagenJugador3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        imagenJugador4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        imagenJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroM.png"))); // NOI18N
        imagenJugador4.setText("Alex");
        imagenJugador4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imagenJugador4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagenJugador4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout areaJugadorLayout = new javax.swing.GroupLayout(areaJugador);
        areaJugador.setLayout(areaJugadorLayout);
        areaJugadorLayout.setHorizontalGroup(
            areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaJugadorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(imagenJugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaJugadorLayout.createSequentialGroup()
                        .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaJugadorLayout.createSequentialGroup()
                        .addComponent(imagenJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        areaJugadorLayout.setVerticalGroup(
            areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaJugadorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(imagenJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hoteles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(areaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenJugador2)
                    .addComponent(imagenJugador3)
                    .addComponent(imagenJugador4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tableroYFondo.add(areaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 280, 320));

        piezaJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerroP.png"))); // NOI18N
        tableroYFondo.add(piezaJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        piezaJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroP.png"))); // NOI18N
        tableroYFondo.add(piezaJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, -1, -1));

        piezaJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SombreroP.png"))); // NOI18N
        tableroYFondo.add(piezaJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        piezaJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DedalP.png"))); // NOI18N
        tableroYFondo.add(piezaJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("No posees ninguna Propiedad");
        tableroYFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, -1));

        getContentPane().add(tableroYFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tablero.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        enAnimacion=true;
        new Thread(new LanzadorDados(this)).start();
    }//GEN-LAST:event_botonJugarActionPerformed

    private void aceptarNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarNotificacionActionPerformed
        panelNotificacion.setVisible(false);
    }//GEN-LAST:event_aceptarNotificacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cliente.solicitarIngreso(new Usuario(jtUsuario.getText(),jtClave.getText(),"",""));
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void actualizarTablero(Tablero tablero){
        tablero.imprimirTablero();
        tableroYFondo.setLayout(null);
        cliente.actualizarPosicion();
        if(tablero.getJugadores().size()>=1){
            dinero.setVisible(true);
            imagenJugador.setVisible(true);
            casas.setVisible(true);
            hoteles.setVisible(true);
            dinero.setText(String.valueOf(tablero.getJugadores().get(cliente.getPosJugador()).getDinero()));
            imagenJugador.setText(cliente.getNombre());
            imagenJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(cliente.getPosJugador(),3))));
            casas.setText(String.valueOf(tablero.getJugadores().get(cliente.getPosJugador()).getCasas()));
            hoteles.setText(String.valueOf(tablero.getJugadores().get(cliente.getPosJugador()).getHoteles()));
        
        }
        mostrarOtrosJugadores(tablero);
        mostrarDado(dado1,tablero.getDado1());
        mostrarDado(dado2,tablero.getDado2());
        botonJugar.setVisible(tablero.isTurno());
        
        /*Prueba de casas
        if (tablero.getJugadores().get(0).getPosicion() instanceof CPropiedad){
            JLabel casa = new JLabel("");
            tableroYFondo.add(casa);
            CPropiedad casilla = (CPropiedad) tablero.getJugadores().get(0).getPosicion();
            casa.setSize(16, 16);
            System.out.println(casilla.getPosCasasX());
            System.out.println(casilla.getPosJugadorX());
            casa.setLocation( casilla.getPosCasasX(),casilla.getPosCasasY());
            casa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casa.png")));
            this.revalidate();
            this.validate();
            this.repaint();
        }
        */
    }
        
    
    public void mostrarDado(JLabel dado, int num){
        if(num==1)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D1.png")));
        else if(num==2)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D2.png")));
        else if(num==3)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D3.png")));
        else if(num==4)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D4.png")));
        else if(num==5)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D5.png")));
        else if(num==6)dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D6.png")));
        pack();
    }   
    
    public void mostrarOtrosJugadores(Tablero tablero){
        int jugadorActual = tablero.obtenerJugador(cliente.getNombre());
        int contador = 1;
        
        if(tablero.getJugadores().size()>=1){
            piezaJugador1.setVisible(true);
            piezaJugador1.setLocation(tablero.getCasillas().get(tablero.getJugadores().get(0).getPosicion()).getPosJugadorX(),tablero.getCasillas().get(tablero.getJugadores().get(0).getPosicion()).getPosJUgadorY());
            piezaJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(0,0))));
            if(jugadorActual!=0){
                mostrarEnJugadores(contador,0,tablero.getJugadores().get(0));
                contador++;
            }
        }
        if(tablero.getJugadores().size()>=2){
            piezaJugador2.setVisible(true);
            piezaJugador2.setLocation(tablero.getCasillas().get(tablero.getJugadores().get(1).getPosicion()).getPosJugadorX(),tablero.getCasillas().get(tablero.getJugadores().get(1).getPosicion()).getPosJUgadorY());
            piezaJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(1,0))));
            if(jugadorActual!=1){
                mostrarEnJugadores(contador,1,tablero.getJugadores().get(1));
                contador++;
            }
            imagenJugador2.setVisible(true);
        }
        if(tablero.getJugadores().size()>=3){
            piezaJugador3.setVisible(true);
            piezaJugador3.setLocation(tablero.getCasillas().get(tablero.getJugadores().get(2).getPosicion()).getPosJugadorX(),tablero.getCasillas().get(tablero.getJugadores().get(2).getPosicion()).getPosJUgadorY());
            piezaJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(2,0))));
            if(jugadorActual!=2){
                mostrarEnJugadores(contador,2,tablero.getJugadores().get(2));
                contador++;
            }
            imagenJugador3.setVisible(true);
        }
        if(tablero.getJugadores().size()>=4){
            piezaJugador4.setVisible(true);
            piezaJugador4.setLocation(tablero.getCasillas().get(tablero.getJugadores().get(3).getPosicion()).getPosJugadorX(),tablero.getCasillas().get(tablero.getJugadores().get(3).getPosicion()).getPosJUgadorY());
            piezaJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(3,0))));
            if(jugadorActual!=3){
                mostrarEnJugadores(contador,3,tablero.getJugadores().get(3));
                contador++;
            }
            imagenJugador4.setVisible(true);
        }
        
    } 
    
    public void mostrarEnJugadores(int pos, int posJugador,Jugador j){
        if(pos==1){
            imagenJugador2.setText(j.getNombre());
            imagenJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(posJugador,2))));
        }
        else if(pos==2){
            imagenJugador3.setText(j.getNombre());
            imagenJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(posJugador,2))));
        }
        else if(pos==3){
            imagenJugador4.setText(j.getNombre());
            imagenJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource(mostrarIcono(posJugador,2))));
        }
        
    }
    
    public void mostrarNotificacion(String titulo, String mensaje){
        panelNotificacion.setVisible(true);
        notificacion.setVisible(true);
        tituloNotificacion.setText(titulo);
        mostrarMensajeNotificacion(mensaje);
        
    }
    
    public void iniciarJuego(){
        panelLogin.setVisible(false);
        tableroYFondo.setVisible(true);
        cliente.enviarJugador();
        
    
    }
    
    public class LanzadorDados implements Runnable{
        PantallaJugadorPrincipal pantalla;

        public LanzadorDados(PantallaJugadorPrincipal pantalla) {
            this.pantalla = pantalla;
        }
        
        
        @Override
        public void run() {
            pantalla.botonJugar.setVisible(false);
            int max =(int)(5+Math.random()*8);
            for(int i=0;i<max;i++){
                int d1 =(int)(1+Math.random()*6);
                int d2 = (int)(1+Math.random()*6);
                pantalla.mostrarDado(pantalla.dado1,d1);
                pantalla.mostrarDado(pantalla.dado2,d2);
                try {
                    TimeUnit.MILLISECONDS.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PantallaJugadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            pantalla.cliente.solicitarMoverse();
            
        }
        
    }
    
    public String mostrarIcono(int icono, int tamaño){
        if(tamaño==0){
            if(icono==0) return "/Imagenes/CarroP.png";
            if(icono==1) return "/Imagenes/DedalP.png";
            if(icono==2) return "/Imagenes/PerroP.png";
            if(icono==3) return "/Imagenes/SombreroP.png";
        }
        else if(tamaño==2){
            if(icono==0) return "/Imagenes/CarroM.png";
            if(icono==1) return "/Imagenes/DedalM.png";
            if(icono==2) return "/Imagenes/PerroM.png";
            if(icono==3) return "/Imagenes/SombreroM.png";
        }
        else if(tamaño==3){
            if(icono==0) return "/Imagenes/CarroG.png";
            if(icono==1) return "/Imagenes/DedalG.png";
            if(icono==2) return "/Imagenes/PerroG.png";
            if(icono==3) return "/Imagenes/SombreroG.png";
        }
        return "";
    }
    
    public void mostrarMensajeNotificacion(String mensaje){
        textoNotificacion.setText("");
        textoNotificacion2.setText("");
        int size = mensaje.length();
        if (size<=45) textoNotificacion.setText(mensaje);
        else{
            textoNotificacion.setText(mensaje.substring(0, 45)+"-");
            textoNotificacion2.setText(mensaje.substring(45));
        }
        
    };
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarNotificacion;
    private javax.swing.JPanel areaJugador;
    private javax.swing.JButton botonJugar;
    private javax.swing.JLabel casas;
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoNotificacion;
    private javax.swing.JLabel hoteles;
    private javax.swing.JLabel imagenJugador;
    private javax.swing.JLabel imagenJugador2;
    private javax.swing.JLabel imagenJugador3;
    private javax.swing.JLabel imagenJugador4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jtClave;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JPanel notificacion;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelNotificacion;
    private javax.swing.JLabel piezaJugador1;
    private javax.swing.JLabel piezaJugador2;
    private javax.swing.JLabel piezaJugador3;
    private javax.swing.JLabel piezaJugador4;
    private javax.swing.JPanel tableroYFondo;
    private javax.swing.JLabel textoNotificacion;
    private javax.swing.JLabel textoNotificacion2;
    private javax.swing.JLabel tituloLogin;
    private javax.swing.JLabel tituloNotificacion;
    // End of variables declaration//GEN-END:variables

}


